networks:
  apps_net:
    external: true
volumes:
  front-justificaai-data:
    driver: local
services:
  front_justificaai:
    image: front_justificai:v1
    container_name: front_justificaai
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5179:5179"
    env_file:
      - .env.local
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M      # Limite máximo de memória
          cpus: "0.5"       # Limite de CPU (metade de um núcleo)
        reservations:
          memory: 256M      # Reserva mínima de memória
    volumes:
      - front-justificaai-data:/app/data  # Mapeamento do volume para o container
    networks:
      - apps_net